### ISSUE TITLE
[제안] Lombok 사용

### ISSUE THREAD

**Issue by xlffm3** [woowacourse-teams/2021-pick-git#103]
![image](https://user-images.githubusercontent.com/56240505/125575344-2d3cdbde-9729-45b1-a7ed-5acf6b5e92e7.png)

이제 슬슬 생산성, 추후 버그 예방을 위해서라도
롬복 사용을 고려해야할 때가 된 것 같습니다.

개인적으로는 getter, setter, toString 등은 lombok을 사용하지 않고
@Builder만을 사용하는 선에서 사용하고싶습니다.

https://cobbybb.tistory.com/14

* 기본 생성자의 접근 레벨을 protected 지정 가능.
* 클래스 레벨에 빌더 사용하지 않고 생성자에만 빌더 추가.

**Comment by da-nyee** [comment]
https://github.com/woowacourse-teams/2021-pick-git/pull/218#issuecomment-884124156
