### ISSUE TITLE
[docs/template] Issue 및 PR Template을 수정한다.

### ISSUE THREAD

**Issue by da-nyee** [woowacourse-teams/2021-pick-git#204]
## 작업 내용
- Issue Template
  - 현재 feature, bug 템플릿만 있는데요.
  - refactor 템플릿도 새로 생성하는 건 어떨까요?
- PR Template
  - 가끔 Linked pull requests를 놓치는 경우가 있는데요.
  - 자동으로 해당 PR이랑 이슈랑 링크되게 템플릿 끝에 `Close #{이슈_번호}` 추가하는 건 어떨까요?

**Comment by yjksw** [comment]
동의합니다~~~ 훨씬 간편하고 깔끔해지겠네요 !!!
