### ISSUE TITLE
[제안] 백엔드 로깅 전략에 대해 논의한다.

### ISSUE THREAD

**Issue by xlffm3** [woowacourse-teams/2021-pick-git#238]
## 구현 기능
* 로깅 전략에 대해 논의가 필요합니다.
* 로깅 프로필 -> prod, local은 file로 관리, test는 console
* 로깅할 내용 -> db, api, 에러 등.
* 로깅 수준 등

**Comment by yjksw** [comment]
저는 ,,
1. 테스트 로깅은 console 관리하는 것에 찬성입니다!! 
2. 로깅 내용은 현재 xml에 명시한 대로 충분하다고 생각합니다!! 
3. 로깅 수준
  -  `<logger name="org.hibernate.type.BasicTypeRegistry" level="WARN">` -> local/test 이지만 로깅내용이 많다고 하니 현재대로  WARN 유지 좋다고 생각해요! 
  - `GlobalApplicationException` 에서 현 어플리케이션에서 정의한 예외에 대해서는 error 레벨, 그 이상의 runtime, db excpetion에 대해서는  warn 레벨 적용한 것도 저는 현상태 그대로 좋다고 생각합니다!!
 
+ 생각해볼만한 것으로 API 응답 및 요청 로깅에 대한 부분이 있었는데, 저는 우선은 불필요한 로그라고 생각해요! 이후에 과도한 성능 저하가 일어났을 때나 예측하지 못하는 에러가 발생했을 경우 현상 분석을 위해서 추가해도 될 것 같다는 생각이 드네요!!

**Comment by xlffm3** [comment]
```xml
  <springProfile name="prod">
    <logger name="com.woowacourse.pickgit" level="INFO">
      <appender-ref ref="prod-file-logger"/>
    </logger>
    <logger name="org.springframework" level="INFO">
      <appender-ref ref="prod-file-logger"/>
    </logger>
    <logger name="org.hibernate.tool.hbm2ddl" level="INFO">
      <appender-ref ref="prod-file-logger"/>
    </logger>
  </springProfile>

  <springProfile name="local">
    <logger name="com.woowacourse.pickgit" level="DEBUG">
      <appender-ref ref="local-file-logger"/>
    </logger>
    <logger name="org.springframework" level="DEBUG">
      <appender-ref ref="local-file-logger"/>
    </logger>
    <logger name="org.hibernate.SQL" level="DEBUG">
      <appender-ref ref="local-file-logger"/>
    </logger>
    <logger name="org.hibernate.tool.hbm2ddl" level="DEBUG">
      <appender-ref ref="local-file-logger"/>
    </logger>
    <logger name="org.hibernate.type.descriptor.sql.BasicBinder" level="DEBUG">
      <appender-ref ref="local-file-logger"/>
    </logger>
    <logger name="org.hibernate.type.descriptor.sql.BasicExtractor" level="DEBUG">
      <appender-ref ref="local-file-logger"/>
    </logger>
  </springProfile>

  <springProfile name="test">
    <logger name="com.woowacourse.pickgit" level="TRACE">
      <appender-ref ref="test-console-logger"/>
    </logger>
    <logger name="org.hibernate.type.descriptor.sql.BasicBinder" level="TRACE">
      <appender-ref ref="test-console-logger"/>
    </logger>
    <logger name="org.hibernate.type.descriptor.sql.BasicExtractor" level="TRACE">
      <appender-ref ref="test-console-logger"/>
    </logger>
  </springProfile>
</configuration>
````

### 1. Test

* 생각해보니 테스트 환경의 경우, hibernate.show-sql=true 주면 콘솔에 어떤 쿼리가 나가는지 로그가 나가기 때문에 sql 관련 로그 설정이 엄청 필요해보이지 않네요.
* BasicBinder와 BasicExtractor는 각각 쿼리에 바인딩되는 파라미터 및 조회 질의 결과를 보여주는 로그를 작성하는데요. 이 부분이 테스트 실패하는 경우 문제 해결에 큰 도움이 될지 의문입니다. (오히려 로그가 너무 많아져서 어느 부분이 문제인지 쉽게 캐치하기 어려울수도 있구요)
* Spring쪽에서 문제가 발생해서 예외가 터지면 (예를 들어 컨테이너 설정 문제로 인해 로드 실패), 테스트의 경우 붉은 글씨로 로그가 알아서 남기 때문에 어디 어느쪽에서 문제가 나는지 빠르게 확인할 수 있는데요. 그래서 Spring 관련 로거가 테스트 환경에서 필요할지...?

### 2. Prod

* Local은 개발자 각각이 제어하는 영역이라 가급적 많은 로그를 남기도록 지정해놨습니다.
* 반면 Prod는 어느정도 수준까지 남겨야할지 고민이네요. ㅎㅎ 요청을 수행하면서 발생하는 sql 쿼리를 모두 남기는게 유의미한가?에 대해서 고민이 좀 되서요! 이 부분에도 의견 남겨주시면 감사
