### ISSUE TITLE
[제안] 유저 검색 API 반환값 수정 제안

### ISSUE THREAD

**Issue by Tanney-102** [woowacourse-teams/2021-pick-git#261]
## 제안 내용
<img width="530" alt="스크린샷 2021-07-27 오후 3 13 41" src="https://user-images.githubusercontent.com/57767891/127105292-f93a521b-d416-474e-9c90-5591079c5662.png">

- 기획상으로는 검색 페이지에서 팔로우, 언팔로우를 할 수 있도록 되어있는데 api 명세 작성 시 놓친 것 같습니다!
- 반환 값을 다음과 같이 변경하도록 제안합니다!
 ### * <strong>혹시 이번 스프린트에서 기능 추가가 부담스럽다면 우선 팔로우 기능을 제외하고 추후 논의해봐도 좋을 것 같습니다.</strong>

### 기존

<요청>
```
GET /api/search?keyword=XXX&page={number}&limit={number}
```

<응답>
```
200 OK 
[
    {
      imageUrl: String,
      username: String,
    }, ...
]
```

### 변경
<요청>
```
GET /api/search?keyword=XXX&page={number}&limit={number}
Authorization: Bearer XXX

// 로그인 시에만 Authorization 포함
```

<응답>
```
200 OK 
[
    {
      imageUrl: String,
      username: String,
      following: Boolean // 비로그인 시에는 null
    }, ...
]
```

**Comment by binghe819** [comment]
브콜~ 좋은 제안이네요!!

제가 이해한 것이 맞는지 확인 부탁드릴게요!

* 로그인 시 -> following 여부 (true/false) 반환
* 비 로그인 시 -> following 여부 null로 반환

**Comment by Tanney-102** [comment]
@binghe819 네네 맞습니당 ㅎㅎ
해당부분을 다음 스프린트로 넘기자는 의견도 있었는데 이에 대해서도 의견 주시면 좋을 것 같아요!
