### ISSUE TITLE
[refactor/seperate_build_gradle] 문서 생성, 소나큐브, 빌드 과정을 분리한다.

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-teams/2021-pick-git#470]
## 구현 기능

현재 빌드단계에서 문서 생성을 의존하고 있으며, 소나큐브똔한 빌드단계를 의존하고 있습니다. 이로 인해 필요없는 테스트 과정이 추가되기도 하고 빌드와 테스트를 분리하지 못하여 실패 시점을 판단하기 어려운 문제점이 있습니다.
이 시점들을 분리하여 관리하여 빌드 시간을 단축시킬 수 있습니다.

<br/>

## 작업 내용

<br/>

**Comment by xlffm3** [comment]
@bperhaps PR 반영으로 해당 이슈 close하겠습니다!
