### ISSUE TITLE
[refactor/post-me] 내 게시글을 불러오는 api 명세에 tag id를 명시한다.

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-teams/2021-pick-git#590]
## 작업 내용
- 포트폴리오 기능에서 tag id가 필요하여 tag 쪽에 id를 명시한다.

### AS-IS
![image](https://user-images.githubusercontent.com/33603557/137771418-2e1ecb9c-6158-45f1-83fd-79331f60d97e.png)

### TO-BE
```
"tags": [
    "tag1": {
        id: Long,
        name: String
    },
    "tag2": {
        id: Long,
        name: String
    },
    ...
]
```

**Comment by yjksw** [comment]
회의를 한 결과, 
- id를 추가하는 방향이 아니라 tag name 리스트를 in query로 한꺼번에 Tag를 호출하는 방법으로 바꿨습니다.
