### ISSUE TITLE
[제안] 로그인 API 명세

### ISSUE THREAD

**Issue by Tanney-102** [woowacourse-teams/2021-pick-git#93]
# 로그인 

## Request
`POST` /api/login/oauth/github

```
// request body

{
  "code": ""
}
```

## Response
```
// response body

{
  "name": "",
  "profileImageUrl": "",
  "accessToken": "",
}
  
```

**Comment by xlffm3** [comment]
@binghe819

**Comment by binghe819** [comment]
전체적인 Flow 말씀 드릴게유!!

## 로그인 버튼 URL
```
Request

GET /api/authorization/github (로그인 버튼 URL)


Response

{
    "url": "https://github.com/login/oauth/authorize?client_id=XXX&redirect_url=http://domain.com/api/afterlogin"
}
```
* 반환받은 url을 그대로 get 요청보내면 Github 로그인 화면으로 이동합니다!
* 그리고 사용자가 Github 로그인을 하여 인증되면 `http://domain.com/api/afterlogin`(추후 배포되면 도메인 이름 변경될 예정)로 리다이렉션이 걸립니다.
  * Github에서 리다이렉션하는 주소 값 : `http://domain.com/api/afterlogin?code=XXX`

<br>

## 리다이렉션 걸리고 깃-들다 서버에서 반환되는 값
```
Response

{
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InBpY2stZ2l0LWxvZ2luIiwiaWF0IjoxNjI2MTU5NTI1LCJleHAiOjE2MjYxNjMxMjV9.EYIq4lIAFUb3ToapWRBHHFpsZHluBNWBAttVMoOxg_o"
}
```

<br>

> 결론적으론 프론트측에선 `GET /api/authorization/github`를 통해 받은 url을 그대로 get하면 Github 로그인으로 이동하고, 인증이되면 자동으로 리다이렉션이 걸려서 저희 서버(깃-들다)에서 Jwt 토큰을 반환합니다!

**Comment by Tanney-102** [comment]
지난번 회의때 이야기하기로는 
github login 페이지로 가는 url을 a태그로 제공하고 redirect url을 프론트쪽 페이지로 지정한 다음에 해당 페이지에서 code를 파싱해 따로 요청하기로 하지 않았었나요?

**Comment by Tanney-102** [comment]
제가 지금 잘못이해하고 있는건지는 모르겠는데

1. 브라우저 : PickGit 로그인 페이지 
request: GET /api/authorization/github
response: content-type json { url }

request: GET https://github.com/login/oauth/authorize?client_id=XXX&redirect_url=http://domain.com/api/afterlogin
response: Github 로그인 페이지

2. 브라우저: Github 로그인 페이지
request: 깃헙 로그인
response: redirect http://domain.com/api/afterlogin?code=XXX

request: GET http://domain.com/api/afterlogin?code=XXX
response: content-json { token }

이러한 방식이라고 생각되는데 브라우저 location이 깃들다의 프론트쪽 페이지가 아닌 상태에서 저 토큰을 어떻게 가져올 수 있을지가 궁금합니다

**Comment by Tanney-102** [comment]
1. 브라우저: 깃들다 로그인 페이지
request: request: GET https://github.com/login/oauth/authorize?client_id=XXX&redirect_url=http://domain.com/api/afterlogin
response: Github 로그인 페이지

2. 브라우저: Github 로그인 페이지
request: 깃헙 로그인
response: redirect 깃들다 oauth로그인 처리 페이지(프론트)

   request: 깃들다 oauth로그인 처리 페이지(프론트)
   reponse: 깃들다 oauth로그인 처리 페이지(프론트)
 
3. 깃들다 oauth로그인 처리 페이지(프론트)
request: GET /api/authorization/github?code={string}
response: content-type json { token }

    save token & login & route to main page

요러 플로우가 더 자연스럽지 않을까요?

**Comment by binghe819** [comment]
# 결론!
* Github redirect_url을 프론트 서버쪽으로 해놓고, 프론트 서버에서 해당 리다이렉션을 받아서 백엔드 서버로 찌르는 걸로!

<br>

## API 명세

<br>

**Github OAuth 로그인 URL 요청**

```
Request GET /api/authorization/github

Response

{
	url: ....
}
```

<br>

**로그인**

```
Request /api/afterlogin?code=XXXX

Response
{
	username: ...,
	token: ....
}
```

## ps. 추후 프론트 서버가 배포되면 해당 서버로 Github Redirect_url을 설정할 수 있도록 알려주세유~
